= gnuplot
// 著者の名前(省略可)<メールアドレス(省略可能)>
// バージョンや作成日(省略可)
:Author:	yossym
:Email:     docomoxyz@gmail.com
:Date:      	2020-09-11
:Revision:  0.1

== 起動、終了

.起動
[source,gnuplot]
----
gnuplot
----

.終了

[source,gnuplot]
----
gnuplot> quit
----

== サンプル描画

----
test
----

----
test palette
----

.ファイル出力
----
gnuplot> set term png
gnuplot> set output "test.png"
gnuplot> test
----

== 色指定

.matlabで使われている”jet”
----
set palette defined ( 0 '#000090',1 '#000fff',2 '#0090ff',3 '#0fffee',4 '#90ff70',5 '#ffee00',6 '#ff7000',7 '#ee0000',8 '#7f0000')
----

== ファイル読み込み

.sample.plt
[source,gnuplot]
----
set title "this is test"
plot sin(x)/x
----

.読み込み
[source,gnuplot]
----
load "sample.plt"
----

=== ファイル出力

.pngとして出力
[source,gnuplot]
----
set term png
set output "xxx.png"
replot
----

=== ポイントや線や色の一覧

[source,gnuplot]
----
set output "test.png"
set terminal png
test
----


== コマンド

=== encoding

	set encoding utf8
	set encoding sjis
	show encoding

=== title

	set tite "グラフのタイトル" font ",20"
	set tite "グラフのタイトル" font "Meiryo,20"
	set tite "グラフのタイトル" font "Meiryo,20" textcolor "blue"

=== xrange

	set xrange [0:10]
	set xr [-10:10]
	set xr []

=== yrange

	set yrange [0:10]
	set yr [-10:10]
	set yr []

=== timefmt

	set timefmt "%Y/%m/%d %H:%M:%S""
	show timefmt

=== Xラベル

	set xlabel "X軸[m]"
	set xlabel "X軸[m]" ",10" textcolor red
	set xlabel 1 "X軸[m]" "Meiryo,10" textcolor red
	unset xlabel 1
	show xlabel

=== Yラベル

	set xlabel "X軸[m]"
	set xlabel "X軸[m]" ",10" textcolor red
	set xlabel 1 "X軸[m]" "Meiryo,10" textcolor red
	unset xlabel 1
	show xlabel

=== 全軸目盛り制御

	set tics 3

	set xtics 3

	set ytics 3

=== grid


	set grid with linewidth 1 linecolor rgb "blue"
	set grid with lw 1 lc rgb "blue"


=== key

	set key









----
gnuplot> show colornames
        There are 111 predefined color names:
  white              #ffffff = 255 255 255
  black              #000000 =   0   0   0
  dark-grey          #a0a0a0 = 160 160 160
  red                #ff0000 = 255   0   0
  web-green          #00c000 =   0 192   0
  web-blue           #0080ff =   0 128 255
  dark-magenta       #c000ff = 192   0 255
  dark-cyan          #00eeee =   0 238 238
  dark-orange        #c04000 = 192  64   0
  dark-yellow        #c8c800 = 200 200   0
  royalblue          #4169e1 =  65 105 225
  goldenrod          #ffc020 = 255 192  32
  dark-spring-green  #008040 =   0 128  64
  purple             #c080ff = 192 128 255
  steelblue          #306080 =  48  96 128
  dark-red           #8b0000 = 139   0   0
  dark-chartreuse    #408000 =  64 128   0
  orchid             #ff80ff = 255 128 255
  aquamarine         #7fffd4 = 127 255 212
  brown              #a52a2a = 165  42  42
  yellow             #ffff00 = 255 255   0
  turquoise          #40e0d0 =  64 224 208
  grey0              #000000 =   0   0   0
  grey10             #1a1a1a =  26  26  26
  grey20             #333333 =  51  51  51
  grey30             #4d4d4d =  77  77  77
  grey40             #666666 = 102 102 102
  grey50             #7f7f7f = 127 127 127
  grey60             #999999 = 153 153 153
  grey70             #b3b3b3 = 179 179 179
  grey               #c0c0c0 = 192 192 192
  grey80             #cccccc = 204 204 204
  grey90             #e5e5e5 = 229 229 229
  grey100            #ffffff = 255 255 255
  light-red          #f03232 = 240  50  50
  light-green        #90ee90 = 144 238 144
  light-blue         #add8e6 = 173 216 230
  light-magenta      #f055f0 = 240  85 240
  light-cyan         #e0ffff = 224 255 255
  light-goldenrod    #eedd82 = 238 221 130
  light-pink         #ffb6c1 = 255 182 193
  light-turquoise    #afeeee = 175 238 238
  gold               #ffd700 = 255 215   0
  green              #00ff00 =   0 255   0
  dark-green         #006400 =   0 100   0
  spring-green       #00ff7f =   0 255 127
  forest-green       #228b22 =  34 139  34
  sea-green          #2e8b57 =  46 139  87
  blue               #0000ff =   0   0 255
  dark-blue          #00008b =   0   0 139
  midnight-blue      #191970 =  25  25 112
  navy               #000080 =   0   0 128
  medium-blue        #0000cd =   0   0 205
  skyblue            #87ceeb = 135 206 235
  cyan               #00ffff =   0 255 255
  magenta            #ff00ff = 255   0 255
  dark-turquoise     #00ced1 =   0 206 209
  dark-pink          #ff1493 = 255  20 147
  coral              #ff7f50 = 255 127  80
  light-coral        #f08080 = 240 128 128
  orange-red         #ff4500 = 255  69   0
  salmon             #fa8072 = 250 128 114
  dark-salmon        #e9967a = 233 150 122
  khaki              #f0e68c = 240 230 140
  dark-khaki         #bdb76b = 189 183 107
  dark-goldenrod     #b8860b = 184 134  11
  beige              #f5f5dc = 245 245 220
  olive              #a08020 = 160 128  32
  orange             #ffa500 = 255 165   0
  violet             #ee82ee = 238 130 238
  dark-violet        #9400d3 = 148   0 211
  plum               #dda0dd = 221 160 221
  dark-plum          #905040 = 144  80  64
  dark-olivegreen    #556b2f =  85 107  47
  orangered4         #801400 = 128  20   0
  brown4             #801414 = 128  20  20
  sienna4            #804014 = 128  64  20
  orchid4            #804080 = 128  64 128
  mediumpurple3      #8060c0 = 128  96 192
  slateblue1         #8060ff = 128  96 255
  yellow4            #808000 = 128 128   0
  sienna1            #ff8040 = 255 128  64
  tan1               #ffa040 = 255 160  64
  sandybrown         #ffa060 = 255 160  96
  light-salmon       #ffa070 = 255 160 112
  pink               #ffc0c0 = 255 192 192
  khaki1             #ffff80 = 255 255 128
  lemonchiffon       #ffffc0 = 255 255 192
  bisque             #cdb79e = 205 183 158
  honeydew           #f0fff0 = 240 255 240
  slategrey          #a0b6cd = 160 182 205
  seagreen           #c1ffc1 = 193 255 193
  antiquewhite       #cdc0b0 = 205 192 176
  chartreuse         #7cff40 = 124 255  64
  greenyellow        #a0ff20 = 160 255  32
  gray               #bebebe = 190 190 190
  light-gray         #d3d3d3 = 211 211 211
  light-grey         #d3d3d3 = 211 211 211
  dark-gray          #a0a0a0 = 160 160 160
  slategray          #a0b6cd = 160 182 205
  gray0              #000000 =   0   0   0
  gray10             #1a1a1a =  26  26  26
  gray20             #333333 =  51  51  51
  gray30             #4d4d4d =  77  77  77
  gray40             #666666 = 102 102 102
  gray50             #7f7f7f = 127 127 127
  gray60             #999999 = 153 153 153
  gray70             #b3b3b3 = 179 179 179
  gray80             #cccccc = 204 204 204
  gray90             #e5e5e5 = 229 229 229
  gray100            #ffffff = 255 255 255

----

== 線種など

      with <style> { {linestyle | ls <line_style>}
                     | {{linetype  | lt <line_type>}
                        {linewidth | lw <line_width>}
                        {linecolor | lc <colorspec>}
                        {pointtype | pt <point_type>}
                        {pointsize | ps <point_size>}
                        {arrowstyle | as <arrowstyle_index>}
                        {fill | fs <fillstyle>} {fillcolor | fc <colorspec>}
                        {nohidden3d} {nocontours} {nosurface}
                        {palette}}
                   }


where <style> is one of 

     lines        dots       steps     vectors      yerrorlines
     points       impulses   fsteps    xerrorbar    xyerrorbars 
     linespoints  labels     histeps   xerrorlines  xyerrorlines
     financebars  surface    arrows    yerrorbar    parallelaxes

or 

     boxes         boxplot        ellipses       histograms  rgbalpha
     boxerrorbars  candlesticks   filledcurves   image       rgbimage
     boxxyerror    circles        fillsteps      pm3d        polygons
     isosurface    zerrorfill

or 

     table

.代表的な線種
[cols="2,3"]
|=====
|with points   | 点で描画する
|with lines    | 線で描画する
|with boxes    | 棒グラフに描画する
|with steps    | 階段状に描画する
|with impulses | インパルス（垂線）で描画する
|with dots     | 小さな点で描画する（データ点が極めて多数あるときに有用）
|=====

=== 描画サンプル

.data.txt
----
1.2    1.5        2.3
1.3    1.6        2.2
1.4    1.7        2.2
1.5    1.75      2.5
----

.samplt.plt
----
plot "data.txt" using 1:2 with lines title "hoge" \
, "data.txt" using 2:3 with points title "fuga"

----

