= VBA
// 著者の名前(省略可)<メールアドレス(省略可能)>
// バージョンや作成日(省略可)
:Author:	yossym
:Email:     docomoxyz@gmail.com
:Date:      	2020-09-06
:Revision:  0.1

:toc:
:sectnums:
:toclevels: 5

:lang: ja
:doctype: book
:docname: VBA
:toclevels: 5
:sectnums:
:sectnumlevels: 5
// :source-highlighter: pygments
:source-language: VBscript
:toc: right
// :toc: left
:toc-title: 目次

== 変数

WorkBook::
        wb
WorkSheet::
        ws
Range::
        rng, rg

最初::
        FirstRow, FirstColumn
最終::
        LastRow, LastColumn


=== 関数系

テキスト読み込み::
	s

Variant::
	Var




== Workbook

=== Workbook 新規

[source,vbscript]
----
Dim wb As Workbook
Applicatioin.SheetsInNewWorkbook = 1
Set wb = Workbook.
----

=== Workbook 開く

[source,vbscript]
----
Workbook.Open "hoge.xlsx"
----

[source,vbscript]
----
Workbook.Open Filename:="hoge.xlsx",ReadOnly:=True
----

[source,vbscript]
----
Dim wb As Workbook
Set wb = Workbook.Open("hoge.xlsx")
----

[source,vbscript]
----
Dim wb As Workbook
Set wb = Workbook.Open(FileName:="hoge.xlsx",ReadOnly:=True)
----

=== Workbook 閉じる

[source,vbscript]
----
Applicatioin.DisplayAlerts=False
wb.Close
Applicatioin.DisplayAlerts=True
----

=== Workbook 保存

[source,vbscript]
----
Workbook.Save
----

[source,vbscript]
----
Dim SaveTime As String
Savetime = Format(Now,"yyyymmdd_hhmmss")

Workbook.SaveAs "hoge.xlsx"
----


== WorkSheets 追加

* アクティブシートの左に追加
[source,vbscript]
----
WorkSheets.Add
WorkSheets.Add before:=ActiveSheet
----




* アクティブシートの左に追加
[source,vbscript]
----
WorkSheets.Add After:=Activesheet
----

* 2番目のシート右に２枚追加
[source,vbscript]
----
Worksheets.Add After:=Worksheets(2),Count:=2
----

* 最終シート？の右にシート追加
[source,vbscript]
----
Worksheets.Add After:=Worksheets(Worksheets.Count)
----


== WorkSheets 削除

* アクティブシート削除
[source,vbscript]
----
Workbooks.Delete
----

== 行の追加


asdf

=== 1行追加
[source,vbscript]
----
Rows(1).Insert
Range("C3").Insert
Rows("2:3").Insert
----

[source,vbscript]
----
Rows("B").Insert
----

=== 複数行追加
[source,vbscript]
----
Range(Columns(2), Columns(4)).Insert
----

=== 1列追加

[source,vbscript]
----
Columns(1).Insert
Columns("C").Insert
Range("C3").EntireColumn.Insert
----

=== 複数列追加

[source,vbscript]
----
Range(Columns(3), Columns(6)).Insert
----


=== 最終行

[source,vbscript]
----
Dim LastRow As Long
LastRow = Cells(Rows.Count, 1).End(xlUp).Row
----

=== 最終列

[source,vbscript]
----
Dim LastColumn As Long
LastColumn = Cells(1, Columns.Count).End(xlToLeft).Column
----

=== Selection


[source,vbscript]
----
Range("A3").CurrentRegion.Selct
----

[source,vbscript]
----
Range("A3").UsedRange.Select
----


== セル

=== セルの指定


[source,vbscript]
----
Range("C3").Select

	   A B C D E
	 ＋ーーーーーーーーーーーーーー
	1｜□□□
	2｜□□□
	3｜□□■
	4｜
	5｜
	6｜
	7｜
	8｜
	9｜
----

* [red]#エラーになる#
[source,vbscript]
----
Range(Cells(3,3)).Select
----

[source,vbscript]
----
Range("A3:B6").Select

	   A B C D E
	 ＋ーーーーーーーーーーーーーー
	1｜
	2｜
	3｜■■
	4｜■■
	5｜■■
	6｜■■
	7｜
	8｜
	9｜
	｜
----

[source,vbscript]
----
Range("A3,B6").Select

	   A B C D E
	 ＋ーーーーーーーーーーーーーー
	1｜
	2｜
	3｜■
	4｜
	5｜
	6｜　■
	7｜
	8｜
	9｜
	｜
----

[source,vbscript]
----
Range("A3","B6").Select
	   A B C D E
	 ＋ーーーーーーーーーーーーーー
	1｜
	2｜
	3｜■■
	4｜■■
	5｜■■
	6｜■■
	7｜
	8｜
	9｜
----

[source,vbscript]
----
Range("A3:B6","C9:D12").Select

	   A B C D E
	 ＋ーーーーーーーーーーーーーー
	1｜
	2｜
	3｜■■■■
	4｜■■■■
	5｜■■■■
	6｜■■■■
	7｜■■■■
	8｜■■■■
	9｜■■■■
	0｜■■■■
	1｜■■■■
	2｜■■■■
	3｜
----

[source,vbscript]
----
Range(Cells(3,3), Cells(6,6)).Select

	   A B C D E
	 ＋ーーーーーーーーーーーーーー
	1｜
	2｜
	3｜　　■■■■
	4｜　　■■■■
	5｜　　■■■■
	6｜　　■■■■
	7｜
----

[source,vbscript]
----
Range("A3:B6,C9:D12").Select

	   A B C D E
	 ＋ーーーーーーーーーーーーーー
	1｜
	2｜
	3｜■■
	4｜■■
	5｜■■
	6｜■■
	7｜
	8｜
	9｜　　■■
	0｜　　■■
	1｜　　■■
	2｜　　■■
	3｜
----



=== セルの追加


[source,vbscript]
----
' 引数なしなら左に移動'
Range("A3:B6").Insert
----

[source,vbscript]
----
Range("A3:B6").Insert shift:=xlShiftToRight
----

* XlInsertShiftDirection 列挙 (Excel)

[options="header"]
|===
 | 名前           | 値    | 説明
 | xlShiftDown    | -4121 | セルを挿入後、下に伸ばす
 | xlShiftToRight | -4161 | セルを挿入後、右に伸ばす
|===

=== セルの値コピー(Fill*)

* 次の使用例は、シート 1 のセル A1 の内容をセル A1:A10 の範囲に複写します。
[source,vbscript]
----
Worksheets("Sheet1").Range("A1:A10").FillDown
----

* 次の使用例は、シート 1 のセル M1 の内容と書式をセル範囲 A1:M1 に複写します。
[source,vbscript]
----
Worksheets("Sheet1").Range("A1:M1").FillLeft
----

* 次の使用例は、シート 1 のセル A1 の内容と書式をセル範囲 A1:M1 に複写します。
[source,vbscript]
----
Worksheets("Sheet1").Range("A1:M1").FillRight
----

* 次の使用例は、シート 1 のセル A10 の内容と書式をセル範囲 A1:A10 に複写します。
[source,vbscript]
----
Worksheets("Sheet1").Range("A1:A10").FillUp
----

=== コピペ

* 普通にコピペ
[source,VBSCRIPT]
----
Range("R25:R30").Select
Selection.Copy
Range("U25").Select
Selection.PasteSpecial
----

* 1列をコピーして1行にペースト
[source,VBSCRIPT]
----
Range("R25:R30").Select
Selection.Copy
Range("U25").Select
Selection.PasteSpecial Transpose:=True
----

=== ソート
* A1:C5の範囲をA1を基準にソート
[source,VBSCRIPT]
----
Range(cells(1,1),cells(5,3))

Call Range("A1:C5").Sort(key1:=Range("A1"), _
    order1:=xlDescending)

Call Range(Cells(1, 1), Cells(5, 3)).Sort(key1:=Range(Cells(1, 1), Cells(1, 1)), _
    order1:=xlDescending)

Call Range(Cells(1, 1), Cells(5, 3)).Sort(key1:=Cells(1, 1), _
    order1:=xlDescending)
----

* A1:C5の範囲をA1,B1を基準にソート
[source,VBSCRIPT]
----
Call Range("A1:C5").Sort(key1:=Range("A1"), _
    order1:=xlAscending, _
    key2:=Range("B1"), _
    order2:=xlAscending)
----

== ファイル

=== ファイル読み込み(sjis,FileSystemObject)

参照設定::
Microsoft ScrptingRuntime

[source,VBSCRIPT]
----
Dim fso As New Scrpting.Filesystemobject
Dim ts as TextSream
Dim s As String

Set ts = fso.OpenTextFile(FileName)

Do While ts.AtEndOfStream <> True
    s = ts.ReadLine
    ...
Loop
ts.Close
----

=== ファイル読み込み(UTF-8,ADODB)

参照設定::
ActiveX Data Objects 6.1 Library

[source,VBSCRIPT]
----

----


=== ファイル書き込み(sjis,FileSystemObject)

参照設定::
Microsoft ScrptingRuntime

[source,VBSCRIPT]
----
Dim fso As New Scrpting.Filesystemobject
Dim ts as TextSream

' ファイルが存在すればサイズ0にして書き込み
Set ts = fso.OpenTextFile(FileName,ForWriting,True)
ts.WriteLine("This is a  pen.")
ts.Close
----

=== ファイル書き込み(UTF-8,ADODB)











=== ファイル一覧取得

参照設定::
Microsoft ScrptingRuntime

[source,VBSCRIPT]
----
Dim fl As File
Dim fso As New Scrpting.Filesystemobject

For Each fl in fso.GetFolder(Path).Files
    fl.Name,Fl.Type
Next
----

=== フォルダ一覧

参照設定::
Microsoft ScrptingRuntime

[source,VBSCRIPT]
----
Dim fd As Folder
Dim fso As New Scrpting.Filesystemobject

For Each fd In fso.getFolder(Path).subFolders
    fd.Name fd.Path
Next
----
=== 特殊フォルダ

参照設定::
Microsoft ScrptingRuntime


=== FileSystemObject オブジェクト

参照設定::
Microsoft ScrptingRuntime




==== メソッド

===== BuildPath メソッド

フォルダーパスとフォルダーまたはファイルの名前を結合し、有効なパス区切り記号と
の組み合わせを返します。

* 構文

[source,vbscript]
----
object.BuildPath (path, name)
----

[options="header"]
|===
 | Part   | Description
 | object | 必須です。 常に FileSystemObject の名前。
 | path   | 必須。 _名前_を組み合わせる既存のパス。 絶対パスまたは相対パスを指定することができ、既存のフォルダーを指定する必要はありません。
 | name   | 必ず指定します。 既存の_パス_に追加されるフォルダーまたはファイルの名前。
|===

* 注釈

BuildPath メソッドでは、必要な場合に限り、既存のパスと名前の間に追加のパス区切
りを挿入します。


===== CopyFile メソッド

1 つまたは複数のファイルを別の場所にコピーします。

* 構文

[source,vbscript]
----
object.CopyFile source, destination, [ overwrite ]
----

[options="header"]
|===
|パーツ |説明
|object |必ず指定します。 object は、常に FileSystemObject の名前です。
|source |必須。 コピーする 1 つ以上のファイルを示す、ファイル指定用文字列。ワイルドカード文字も使用できます。
|destination |必須です。 source から 1 つ以上のファイルをコピーする先を指定する文字列。 ワイルドカード文字は使用できません。
|overwrite |省略可能。 既存のファイルを上書きできるかどうかを示すブール値です。 True の場合はファイルが上書きされ、False の場合は上書きされません。 既定値は True です。 destination に読み取り専用属性が設定されている場合は、overwrite の値にかかわらず CopyFile は失敗します。
|===

* 解説

ワイルドカード文字を使用できるのは、 source 引数の最後のパス コンポーネントだ
けです。 たとえば、以下を使用できます。

[source,vbscript]
----
FileSystemObject.CopyFile "c:\mydocuments\letters\*.doc", "c:\tempfolder\"
----

以下のようには使用できません。

[source,vbscript]
----
FileSystemObject.CopyFile "c:\mydocuments\*\R1???97.xls", "c:\tempfolder"
----

source にワイルドカード文字が含まれている場合や、destination がパスの区切り文
字 (**) で終わっている場合は、destination は一致するファイルのコピー先となる既
存のフォルダーと見なされます。 それ以外の場合は、destination は作成するファイ
ルの名前と見なされます。 いずれの場合も、個々のファイルのコピー時に起こり得る
ことは 3 つあります。


1. destination が存在しない場合は、source がコピーされます。 これは通常のケー
   スです。

2. destination が既存のファイルの場合、 overwrite が False のときはエラーが発
   生します。 True のときは既存のファイルを上書きして source がコピーされます。

3. destination がディレクトリの場合は、エラーが発生します。

source でワイルドカード文字が使用されていて、どのファイルとも一致しなかった場
合も、エラーが発生します。 いずれかのエラーが発生した時点で CopyFile メソッド
の実行は停止されます。 エラーが発生するまでに行われた変更を取り消したり元に戻
したりする処理は一切行われません。

===== CopyFolder メソッド

フォルダーを再帰的に別の場所にコピーします。

* 構文

[source,vbscript]
----
object.CopyFolder source, destination, [ overwrite ]
----

[options="header"]
|===
|パーツ |説明
|object |必ず指定します。 常に FileSystemObject の名前。
|source |必須。 コピーする 1 つ以上のフォルダーを指定する文字列です。ワイルドカード文字を使用できます。
|destination |必須です。 source のフォルダーとサブフォルダーのコピー先を指定する文字列です。 ワイルドカード文字は使用できません。
|overwrite |省略可能。 既存のフォルダーを上書きするかどうかを示す ブール 値です。 True の場合はファイルが上書きされ、 False の場合は上書きされません。 既定値は True です。
|===

* 解説

ワイルドカード文字を使用できるのは、 source 引数の最後のパス コンポーネントだ
けです。 たとえば、以下を使用できます。

[source,vbscript]
----
FileSystemObject.CopyFolder "c:\mydocuments\letters\*", "c:\tempfolder\"
----

以下のようには使用できません。

[source,vbscript]
----
FileSystemObject.CopyFolder "c:\mydocuments\*\*", "c:\tempfolder\"
----

source にワイルドカード文字が含まれている場合や、destination がパスの区切り文
字 ()) で終わっている場合は、destination は一致するフォルダーとサブフォルダー
のコピー先となる既存のフォルダーと見なされます。 

それ以外の場合は、destinationは作成するフォルダーの名前と見なされます。 

いずれの場合も、個々のフォルダーがコピーされるときに起こり得ることは 4 つあり
ます。


1. destination が存在しない場合は、source フォルダーとそのすべての内容がコピー
   されます。 これは通常のケースです。

2. destination が既存のファイルの場合は、エラーが発生します。

3. destination がディレクトリの場合は、フォルダーとそのすべての内容のコピーを
   しようとします。 source に含まれているファイルが destination に既に存在する
場合は、overwrite が False に設定されているとエラーが発生します。 それ以外の場
合、ファイルを既存のファイルにコピーしようとします。

4. destination が読み取り専用のディレクトリで、overwrite が False の場合、既存
   の読み取り専用のファイルをそのディレクトリにコピーしようとするとエラーが発
生します。

source でワイルドカード文字が使用されていて、どのフォルダーとも一致しなかった
場合も、エラーが発生します。

CopyFolder メソッドは、最初のエラーが発生した時点で処理を中止します。 エラーが
発生するまでに行われた変更を取り消したり元に戻したりする処理は一切行われません。

===== CreateFolder メソッド

フォルダーを作成します。

* 構文

[source,vbscript]
----
object.CreateFolder (foldername)
----

[options="header"]
|===
|パーツ |説明
|object |必須です。 常に FileSystemObject の名前。
|foldername |必ず指定します。 作成するフォルダーを識別する 文字列式です。
|===

* 注釈

指定したフォルダーがすでに存在する場合は、エラーが発生します。




===== CreateTextFile メソッド

指定されたファイル名を作成し、ファイルの読み取りまたは書き込みに使用できる**TextStream** オブジェクトを返します。


* 構文


[source,vbscript]
----
object.CreateTextFile (filename, [ overwrite, [ unicode ]])
----

[options="header"]
|===
|パーツ |説明
|object |必須です。 常に**FileSystemObject** または**Folder** オブジェクトの名前を指定します。
|filename |必須。 作成するファイルを示す 文字列式。
|overwrite |省略可能。 既存のファイルを上書きできるかどうかを示す Boolean 値。 ファイルを上書きできる場合は True 、上書きできない場合は False です。 省略した場合、既存のファイルは上書きできます。
|unicode |省略可能。 Unicode ファイルを作成するか、ASCII ファイルを作成するかを示す Boolean 値です。 Unicode ファイルとして作成する場合は True 、ASCII ファイルとして作成する場合は False です。 省略した場合は、ASCII ファイルとみなされます。
|===

* 注釈

次のコードは、 CreateTextFileメソッドを使用して、テキストファイルを作成して開
く方法を示しています。 _Overwrite_引数がFalseの場合、または指定されていない場
合は、既に存在する_ファイル名_に対してエラーが発生します。


[source,vbscript]
----
Sub CreateAfile
    Set fs = CreateObject("Scripting.FileSystemObject")
    Set a = fs.CreateTextFile("c:\testfile.txt", True)
    a.WriteLine("This is a test.")
    a.Close
End Sub
----

===== DeleteFile メソッド

指定したファイルを削除します。

* 構文

[source,vbscript]
----
object.DeleteFile filespec, [ force ]
----


[options="header"]
|===
|パーツ |説明
|object |必須です。 常に FileSystemObject の名前。
|filespec |必須。 削除するファイルの名前です。 __ 最後のパス コンポーネントではワイルドカード文字を使用できます。
|force |省略可能。 読み取り専用属性が設定されているファイルを削除する場合は、 Trueを指定するブール型 (Boolean) の値を指定します。False(既定値)。
|===


* 注釈

一致するファイルが見つからない場合はエラーが発生します。 DeleteFile メソッドは、
最初のエラーが発生した時点で中止されます。 エラーが発生する前に行われた変更は
ロールバックされません (元に戻されません)。

===== DeleteFolder メソッド

指定したフォルダーおよびその内容を削除します。























































































== Collection, Dictionary


[cols="1,4,4",options="header"]
|===
||Collection|Dictionary
|宣言|Dim c As New Collection| Dim d As New Scripting.Dictionary
| 追加| c.Add Item:=100,key:="This is a pen." +
c.Add   +
c.Add 200."This"| d.Add key:="Orange",Item:=100 +
d.Add "Apple",200
|item取得|a|b
|===








== グラフ

=== グラフ作成

[source,VBSCRIPT]
----
Dim rng As Range

    Set rng = Range("C1").CurrentRegion

With ActiveSheet.Shapes.AddChart.Chart
    .ChartType = xlXYScatterLines
    .SetSourceData rng
End With
----


* Xlcharttype クラス列挙 (Excel)

[options="header"]
|===
 | 名前                       | 値    | 説明
 | xl3DBarClustered           | 60    | 3-D 集合横棒
 | xl3DBarStacked             | 61    | 3-D 積み上げ横棒
 | xl3DBarStacked100          | 62    | 3-D 100% 積み上げ横棒
 | xl3DColumn                 | -4100 | 3-D 縦棒
 | xl3DColumnClustered        | 54    | 3-D 集合縦棒
 | xl3DColumnStacked          | 55    | 3-D 積み上げ縦棒
 | xl3DColumnStacked100       | 56    | 3-D 100% 積み上げ縦棒
 | xlLine                     | 2/4   | 折れ線
 | xlLineMarkers              | 65    | マーカー付き折れ線
 | xlLineMarkersStacked       | 66    | マーカー付き積み上げ折れ線
 | xlLineMarkersStacked100    | 67    | マーカー付き 100% 積み上げ折れ線
 | xlLineStacked              | 63    | 積み上げ折れ線
 | xlLineStacked100           | 64    | 100% 積み上げ折れ線
 | xlXYScatter                | -4169 | 散布図
 | xlXYScatterLines           | 74    | [red]#折れ線付き散布図#
 | xlXYScatterLinesNoMarkers  | 75    | 折れ線付き散布図 (データ マーカーなし)
 | xlXYScatterSmooth          | 72    | 平滑線付き散布図
 | xlXYScatterSmoothNoMarkers | 73    | 平滑線付き散布図 (データ マーカーなし)
|===

=== グラフのタイトル変更

[source,VBSCRIPT]
----
With ActiveSheet.ChartObjects(1).Chart
    .HasTitle = True	'　まずは有効にしてから内容を指定する
    .ChartTitle.Text = "タイトル"
End With
----

[source,VBSCRIPT]
----
ActiveSheet.ChartObjects(1).Select
With ActiveChart
    .HasTitle = True	'　まずは有効にしてから内容を指定する
    .ChartTitle.Caption = "title"
End With
----

=== 軸の設定
==== 軸のタイトル

[source,VBSCRIPT]
----
' グラフのX軸(横軸)のタイトルを設定
ActiveChart.Axes(xlCategory, xlPrimary).HasTitle = True
ActiveChart.Axes(xlCategory, xlPrimary).AxisTitle.Characters.Text = "X軸タイトル"
----

[source,VBSCRIPT]
----
' グラフのY軸(縦軸)のタイトルを設定
ActiveChart.Axes(xlValue, xlPrimary).HasTitle = True
ActiveChart.Axes(xlValue, xlPrimary).AxisTitle.Characters.Text = "Y軸タイトル" 
----

==== 横軸？の最小値、最大値


=== マーカー設定

markersize::
2 から 72

* XlMarkerStyle 列挙 (Excel)
折れ線グラフ、散布図、またはレーダー チャートで、データ要素またはデータ系列の
マーカーのスタイルを設定します。
[options="header"]
|===
 | 名前                   | 値    | 説明
 | xlMarkerStyleAutomatic | -4105 | 自動マーカー
 | xlMarkerStyleCircle    | ~     | 円形のマーカー
 | xlMarkerStyleDash      | -4115 | 長い棒のマーカー
 | xlMarkerStyleDiamond   | pbm-2 | ひし形のマーカー
 | xlMarkerStyleDot       | -4118 | 短い棒のマーカー
 | xlMarkerStyleNone      | -4142 | マーカーなし
 | xlMarkerStylePicture   | -4147 | 画像マーカー
 | xlMarkerStylePlus      | i-9   | 正符号 (+) 付きの四角形のマーカー
 | xlMarkerStyleSquare    | 1-d   | 四角形のマーカー
 | xlMarkerStyleStar      | 5     | アスタリスク (*) 付きの四角形のマーカー
 | xlMarkerStyleTriangle  | 1/3   | 三角形のマーカー
 | xlMarkerStyleX         | -4168 | X 印付きの四角形のマーカー
|===



[source,VBSCRIPT]
----
Dim Co As ChartObject
Dim Sc As Series

For Each Co In ActiveSheet.ChartObjects
    Debug.Print Co.Name

    For Each Sc In Co.Chart.SeriesCollection
        Debug.Print Sc.MarkerSize
        Debug.Print Sc.MarkerStyle

        Sc.MarkerSize = 12
        Sc.MarkerStyle
    Next
Next
----





//	vim:fileencoding=utf-8:ff=unix:
