all:	BubbleSort QuickSort MergesSort MergesSort2 BinarySearch ReversePolishNotation 

BubbleSort: BubbleSort.c
	gcc BubbleSort.c -o BubbleSort

QuickSort: QuickSort.c
	gcc QuickSort.c -o QuickSort

MergesSort: MergesSort.c
	gcc MergesSort.c -o MergesSort


MergesSort2: MergesSort2.c
	gcc MergesSort2.c -o MergesSort2

BinarySearch: BinarySearch.c*
	gcc BinarySearch.c -o BinarySearch


ReversePolishNotation: ReversePolishNotation.c
	gcc -ansi ReversePolishNotation.c -o  ReversePolishNotation


